/* Generated by Edge Impulse
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Generated on: 04.11.2022 23:27:20

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#if defined __GNUC__
#define ALIGN(X) __attribute__((aligned(X)))
#elif defined _MSC_VER
#define ALIGN(X) __declspec(align(X))
#elif defined __TASKING__
#define ALIGN(X) __align(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

constexpr int kTensorArenaSize = 320;

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};
enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};
struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};
struct NodeInfo_t { // subset of TfLiteNode used for initialization from constant memory
  struct TfLiteIntArray* inputs;
  struct TfLiteIntArray* outputs;
  void* builtin_data;
  used_operators_e used_op_index;
};

TfLiteContext ctx{};
TfLiteTensor tflTensors[11];
TfLiteEvalTensor tflEvalTensors[11];
TfLiteRegistration registrations[OP_LAST];
TfLiteNode tflNodes[4];

const TfArray<2, int> tensor_dimension0 = { 2, { 1,84 } };
const TfArray<1, float> quant0_scale = { 1, { 0.240674689412117, } };
const TfArray<1, int> quant0_zero = { 1, { -72 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const ALIGN(16) int8_t tensor_data1[20*84] = { 
  -93, -87, -76, 16, -20, 10, -106, -91, -100, 18, 112, -63, -85, 110, 51, 122, 113, -40, 86, -81, 107, -113, 117, -92, -73, -73, -113, 50, -49, -44, -79, -110, 25, 109, 37, -51, -65, 83, 34, -13, 84, 122, 81, 64, -103, 38, -27, 58, -57, 20, 62, 98, -105, 97, 18, 26, 14, -25, -18, 4, 15, -34, -65, -34, -58, -34, 59, 56, -2, -93, 106, -75, -13, 11, -22, 115, 73, 92, -10, 73, 81, 55, 15, 81, 
  16, 28, 1, -47, 27, 117, 79, 102, -101, 81, 65, -60, -26, -106, -71, -50, -47, -103, 87, 56, -9, -67, -99, -71, 39, -71, 31, 59, -67, 7, 100, 115, -119, -22, -114, 108, -40, 68, 86, -61, -63, 23, 25, 4, -103, -115, 33, -6, -23, -68, 77, 123, -114, -60, 113, -20, -111, 122, -25, -92, 107, 9, -70, 76, -42, -63, 43, -83, 75, -30, -126, 64, -33, -68, 66, 14, -96, -110, 71, -113, 95, -73, -106, -124, 
  0, -122, -98, 52, -1, 29, -118, -29, -78, 13, -41, -30, -93, -28, 67, -104, -85, -30, 103, -119, 85, -18, -63, 25, -55, 105, 12, -63, -19, -74, -81, 93, -110, 50, -83, 40, 30, -17, -60, -78, 102, -22, -4, -10, -29, 13, 86, -31, 126, -98, 115, -3, 23, -86, 78, 65, 77, 34, 39, 92, 43, -119, -109, 44, 58, -92, -59, 11, 65, 112, 91, 55, -46, 119, -43, 73, -86, -32, -93, -29, 30, -58, -90, 40, 
  -121, -33, -98, 51, 32, 37, -86, 20, 19, 108, 1, -108, 19, 55, 11, -61, -33, -27, 117, 74, -124, -79, 125, -10, -17, 115, 8, -40, 96, 24, 1, 91, 8, -101, -27, 93, 30, -24, -92, 7, 7, -23, -28, 69, -93, -79, 92, -92, 71, 77, 106, -71, -48, 113, -115, -73, 67, 3, 81, -87, -117, -66, -26, 80, -69, 37, -38, -122, -120, 45, 59, -43, 0, -76, 14, -89, -105, 49, -62, 72, 73, -69, -69, 16, 
  1, 70, -75, 78, 40, 111, -95, -49, 24, 38, 41, 4, -8, -26, -106, -5, -61, -55, 28, 23, 20, -51, -48, 28, -14, -57, 108, 51, 114, -1, 8, -66, -62, 69, -64, -47, 71, 64, -92, -64, 53, -102, -82, -33, -116, -6, 103, 94, 66, 40, 53, -113, 24, -68, 80, -27, 74, -96, 53, 35, -89, 26, -41, -72, 120, -8, 21, -81, -26, -121, -49, -9, -16, 26, 27, 47, 40, 31, -10, 116, -29, 62, 71, -75, 
  64, -70, -23, -21, -3, 47, 31, 43, -2, -103, -62, -76, 114, -59, 92, 24, -63, 44, 84, 106, -60, -117, -25, -40, -85, 58, 21, -49, 69, 42, 58, 118, 5, 113, -35, 78, -12, 35, 121, -67, -3, 32, 108, 68, -35, 78, -116, 76, -19, -11, -20, 6, -41, -54, -21, 78, 34, -47, 80, 12, -27, 0, 103, 7, 27, -1, 77, 51, 22, -92, -120, -52, -62, -116, -63, -114, 31, 124, 44, 56, -112, 30, 35, 4, 
  -93, 113, -16, -45, -48, 37, 37, -28, -58, 67, -104, -94, -124, -89, 108, 30, -26, 59, 34, -44, 23, -15, 115, -94, 32, 2, -61, 21, 31, -34, 55, -36, -78, -10, -45, -53, 28, 86, 11, -49, 98, 4, -109, -67, -18, -4, 91, 107, 66, 56, 45, 15, 84, -44, -118, 60, -70, 56, 9, 19, 48, -35, 19, -40, -52, -106, 40, -34, -57, -16, -112, 66, -22, 54, -48, -69, 30, 36, 99, 27, 59, 18, -43, 3, 
  -41, 122, -84, -29, -103, 115, 18, -116, 100, -97, 79, -67, -90, -55, -69, -13, -2, -99, 7, -35, -39, -99, -120, -25, -20, -108, 87, 38, 46, 87, -110, 104, -110, -64, 13, 39, -123, 28, 54, 43, 15, -112, 79, -82, -82, 94, 55, 98, 27, 3, 113, 40, -57, 114, 49, 14, 0, 110, -40, -72, -19, 63, 37, 93, -111, 39, 51, -85, 79, -73, -118, 105, -41, 120, 44, 59, 18, 7, 100, 97, 88, 108, -13, -9, 
  38, 51, 46, -120, 78, 58, -40, -25, 52, -98, -124, 118, 9, -48, -126, -77, 22, -22, 90, -1, -15, -35, -23, -67, -53, 111, -107, 28, 99, -2, -44, 46, -54, 50, 87, 38, -20, 14, -106, 31, 63, -103, -88, 83, -35, 7, 98, 61, -87, 106, -125, -93, 26, -87, -37, 0, -105, 44, 73, 36, -21, 92, -67, 123, 106, 110, -124, 18, 5, -126, 48, -83, 55, 123, -87, 114, 53, 67, 104, -19, -58, -32, 86, -43, 
  -5, 25, 12, 61, -109, -5, -9, -47, 63, -22, 3, -39, -61, -6, 11, -52, 34, 110, 101, -100, 79, -79, -10, 105, 95, -92, -43, -78, 109, 72, -96, 37, -5, -91, -18, 106, -13, 93, -7, 91, -88, -54, 65, 72, 37, -98, 82, -12, -39, 89, -31, 124, -74, 122, 88, -119, -96, -49, 68, 35, -71, -44, 118, -81, 112, 105, 114, -69, 90, 52, 14, -52, -64, 23, 51, 2, 82, 82, 52, -79, -2, -98, -48, 37, 
  -99, -103, -118, -94, 117, -42, 41, -3, 17, 85, 9, 107, 23, 105, -14, -91, -78, 75, -39, -13, -67, 7, 79, -112, -54, 40, -91, 71, 44, -103, 120, -23, -117, -2, 110, 46, -45, 16, -81, -11, -49, 6, 101, 109, 41, 79, 23, 76, -51, -116, 113, -59, -100, 3, 76, -80, 18, 104, -120, 114, -71, 24, 74, -110, -91, -62, 102, -32, -123, -65, -51, -19, -70, -65, 37, -58, -99, -107, 64, 81, 88, 113, -67, -103, 
  103, 68, -6, -21, 14, 122, 31, 87, 96, 116, -28, 102, 16, -85, -76, 54, 17, 73, 97, 91, 62, -48, -5, 28, 87, -88, -26, 99, -79, 76, -109, 50, -82, -46, 89, -98, 100, 60, 100, -54, -51, -36, -124, -113, -107, -13, -123, -1, -6, 19, -31, -13, 101, 124, 120, -64, 98, 48, -117, 55, -31, -18, 78, 14, 11, 77, 90, -74, 45, 59, -86, -62, 2, 121, -42, 31, -82, 46, -69, -26, -97, -43, 52, 104, 
  48, 85, 22, -72, 96, -40, 34, -54, -18, 116, -9, -61, -90, 103, 110, -120, 64, -8, -120, -26, -116, -25, 112, -20, -104, -14, -93, 38, 98, -52, 83, -42, -40, 105, -107, -70, -66, -13, -94, 115, -28, 28, 22, 95, -11, -54, 73, -52, -19, 52, -38, -43, -40, -95, 98, 84, 88, 3, 73, 51, -94, -72, 43, -16, -31, 78, 110, 106, 106, -102, -119, -100, 34, -13, -104, 86, 3, 37, -66, 51, 10, -11, 109, -16, 
  13, 30, -37, 84, 17, -31, 61, -25, 38, 93, 120, 108, 61, -51, 5, 26, -74, -64, 35, 100, -122, -46, 53, -50, -124, 99, 70, 21, 108, -56, -124, 127, 37, 59, 86, 61, 111, -74, 70, -116, -40, -9, 82, -36, -73, 11, -68, -9, -3, 116, -80, -78, -14, -28, 81, 72, 23, 115, -114, -53, -3, 4, 120, -19, 0, 80, 42, 80, -125, 109, 97, -100, 0, 46, 114, -94, 46, 30, -41, 125, 31, -66, 68, -20, 
  -73, -124, 125, -60, 58, -42, 64, 78, 12, -45, -105, -21, -103, -34, 13, -19, -67, -58, -54, -72, 28, 52, -72, 46, 72, 6, -93, -17, -51, 9, 20, -4, 89, 83, 101, -121, 31, 12, -91, -41, 0, -99, 87, -111, -46, -2, 77, -120, 88, 12, -94, 7, 73, 61, -22, -57, -45, 14, 91, 97, -123, 78, -28, -33, -117, 10, 73, 109, -92, -114, 89, -19, 99, 3, -38, 35, 100, -14, -34, -6, 59, -116, -52, 59, 
  -78, 119, -39, 44, -30, 108, -76, -62, -17, 100, -74, 57, -49, -35, 123, -96, -11, 86, 78, 85, 29, -55, 31, -101, -57, -37, 76, 45, 11, 11, -116, -101, -109, 73, 80, -40, -33, 77, -7, 92, 105, -73, 98, -15, -50, 74, -115, 116, -46, 83, -15, 69, 30, 41, 25, 69, -16, -51, -19, -101, 74, -66, -94, -46, -9, 59, -69, -112, -115, -35, 101, -22, 31, -63, -50, 94, -53, -51, -88, 122, 24, 119, 79, -66, 
  -94, 107, 74, 21, -5, -1, -14, -60, -15, 39, 5, -101, -71, -112, -81, 59, 87, 60, -104, -15, -59, -113, -57, 94, 78, 48, -27, 15, 124, 116, 9, -23, -11, 78, 31, 34, -12, -41, -98, 50, 33, 122, -71, -93, 54, 39, 63, 88, 119, 32, 110, 99, -22, 35, -31, 17, -103, -18, 7, -54, -54, -42, -29, 117, -30, -41, -18, 43, 6, 122, -48, -96, 82, -20, 30, -115, 101, 31, 68, 121, 61, 123, 48, -119, 
  -55, 8, -118, -108, 110, -52, 22, 89, -72, 11, 12, 54, 26, -39, -19, -36, 6, -21, -67, 100, -113, -35, 70, -101, 110, -14, -89, 122, 74, 66, 74, 22, 22, 29, -111, -116, 113, 22, -101, 23, -96, 79, -94, 97, 119, 113, 76, 109, 14, -90, -51, 84, -57, 113, 118, -84, -11, -36, 50, -103, 94, -31, 83, 96, 107, -37, -44, -53, -14, 25, 93, 85, -120, -111, 59, 95, -104, -43, 77, -116, 84, -122, -53, -123, 
  -83, -26, 101, 108, 75, 48, -2, -84, -34, -31, -106, -83, 92, -13, -54, 88, -49, -21, -105, -20, 79, -109, -38, 123, -80, -104, 93, -33, 25, -7, 70, 47, 101, 13, 54, 80, 54, -15, 28, 76, -43, -124, 37, -49, 119, 96, -95, 57, 66, 10, 12, -104, -89, -55, 46, -91, 18, 50, -118, 37, 12, -31, 124, -100, 92, 47, -94, 112, -91, 70, 42, -65, -7, -103, 111, -76, -70, -72, 69, -67, -95, 66, -54, -114, 
  -37, 56, 85, 60, 27, -5, 1, -108, 110, 112, -31, 94, -7, -37, 103, 40, 28, -116, 36, -19, -39, 71, 109, -110, 84, 116, -2, 115, -111, -124, -119, -88, 127, 64, 40, 17, 99, -59, 65, -29, -98, -52, 115, 47, -72, 20, -16, 89, -57, -126, 108, 87, -39, -38, -43, 3, 103, -111, 19, -44, 33, -91, 35, -94, -69, 100, 118, 85, 18, -73, 93, -72, 11, -49, -106, 81, 65, 32, -34, 100, 0, 108, -25, 23, 
};
const TfArray<2, int> tensor_dimension1 = { 2, { 20,84 } };
const TfArray<1, float> quant1_scale = { 1, { 0.001902002957649529, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const ALIGN(16) int32_t tensor_data2[20] = { -2, -3, 3, 3, 0, 3, 0, 0, 0, 3, 3, -3, 2, -3, 3, -3, 0, 3, 3, -3, };
const TfArray<1, int> tensor_dimension2 = { 1, { 20 } };
const TfArray<1, float> quant2_scale = { 1, { 0.00045776396291330457, } };
const TfArray<1, int> quant2_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&quant2_zero, 0 };
const ALIGN(16) int8_t tensor_data3[10*20] = { 
  -79, -4, 35, 21, 103, -75, -33, 21, -104, -113, -39, -68, 111, 100, -35, 1, -108, 17, -37, 15, 
  -80, 18, -62, 48, 30, 11, 86, -54, -45, -89, 20, -95, -29, -38, -95, -106, -51, 81, 59, -106, 
  -96, 85, 30, -62, 79, -2, 52, -54, 98, 93, -72, -56, 39, -117, 39, -40, -28, 121, -109, -36, 
  -81, -23, -75, -101, -18, 56, 78, 93, 108, -91, 95, 48, 2, -79, -29, 121, 26, 35, 32, -82, 
  18, 8, -67, -94, -122, 105, -43, -7, -73, 121, 6, -120, -107, 44, -20, 23, 23, -111, 119, 29, 
  74, 100, -98, 10, -85, -24, 4, -27, 116, -116, -127, 117, -95, 57, -63, 97, -106, -10, -106, 86, 
  97, -38, 14, 97, 77, -35, 15, 57, 52, 105, -60, 72, -123, -11, -8, -11, 49, -26, 45, -56, 
  -68, 110, -69, -117, -25, -20, -36, -100, 107, 81, 79, 113, -22, -7, -28, -48, -71, 20, -51, 54, 
  -84, 80, 8, 57, 115, -4, 70, -119, -27, -89, 51, 90, 109, 122, -21, 58, -97, 111, -2, 4, 
  -33, 39, 26, 96, -90, 73, 87, -68, 93, -43, -24, 37, -103, -41, -99, 27, 121, 115, -41, 115, 
};
const TfArray<2, int> tensor_dimension3 = { 2, { 10,20 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0034893518313765526, } };
const TfArray<1, int> quant3_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&quant3_zero, 0 };
const ALIGN(16) int32_t tensor_data4[10] = { -7, 0, 0, 0, -7, -7, -5, -6, -7, 7, };
const TfArray<1, int> tensor_dimension4 = { 1, { 10 } };
const TfArray<1, float> quant4_scale = { 1, { 0.00019897021411452442, } };
const TfArray<1, int> quant4_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&quant4_zero, 0 };
const ALIGN(16) int8_t tensor_data5[2*10] = { 
  -37, -127, -11, -113, 8, -85, 56, 79, 1, 48, 
  74, -114, -12, 105, 103, 68, 60, -3, 30, -3, 
};
const TfArray<2, int> tensor_dimension5 = { 2, { 2,10 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0055145043879747391, } };
const TfArray<1, int> quant5_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const ALIGN(8) int32_t tensor_data6[2] = { 4, -4, };
const TfArray<1, int> tensor_dimension6 = { 1, { 2 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00035590902552939951, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.057022113353013992, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.064540527760982513, } };
const TfArray<1, int> quant8_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.054218605160713196, } };
const TfArray<1, int> quant9_zero = { 1, { -72 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<2, int> tensor_dimension10 = { 2, { 1,2 } };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant10_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,1,2 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,3,4 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,5,6 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
const TensorInfo_t tensorData[] = {
  { kTfLiteArenaRw, kTfLiteInt8, tensor_arena + 0, (TfLiteIntArray*)&tensor_dimension0, 84, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant0))}, },
  { kTfLiteMmapRo, kTfLiteInt8, (void*)tensor_data1, (TfLiteIntArray*)&tensor_dimension1, 1680, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant1))}, },
  { kTfLiteMmapRo, kTfLiteInt32, (void*)tensor_data2, (TfLiteIntArray*)&tensor_dimension2, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant2))}, },
  { kTfLiteMmapRo, kTfLiteInt8, (void*)tensor_data3, (TfLiteIntArray*)&tensor_dimension3, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant3))}, },
  { kTfLiteMmapRo, kTfLiteInt32, (void*)tensor_data4, (TfLiteIntArray*)&tensor_dimension4, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant4))}, },
  { kTfLiteMmapRo, kTfLiteInt8, (void*)tensor_data5, (TfLiteIntArray*)&tensor_dimension5, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant5))}, },
  { kTfLiteMmapRo, kTfLiteInt32, (void*)tensor_data6, (TfLiteIntArray*)&tensor_dimension6, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant6))}, },
  { kTfLiteArenaRw, kTfLiteInt8, tensor_arena + 96, (TfLiteIntArray*)&tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant7))}, },
  { kTfLiteArenaRw, kTfLiteInt8, tensor_arena + 0, (TfLiteIntArray*)&tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant8))}, },
  { kTfLiteArenaRw, kTfLiteInt8, tensor_arena + 16, (TfLiteIntArray*)&tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant9))}, },
  { kTfLiteArenaRw, kTfLiteInt8, tensor_arena + 0, (TfLiteIntArray*)&tensor_dimension10, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&quant10))}, },
};const NodeInfo_t nodeData[] = {
  { (TfLiteIntArray*)&inputs0, (TfLiteIntArray*)&outputs0, const_cast<void*>(static_cast<const void*>(&opdata0)), OP_FULLY_CONNECTED, },
  { (TfLiteIntArray*)&inputs1, (TfLiteIntArray*)&outputs1, const_cast<void*>(static_cast<const void*>(&opdata1)), OP_FULLY_CONNECTED, },
  { (TfLiteIntArray*)&inputs2, (TfLiteIntArray*)&outputs2, const_cast<void*>(static_cast<const void*>(&opdata2)), OP_FULLY_CONNECTED, },
  { (TfLiteIntArray*)&inputs3, (TfLiteIntArray*)&outputs3, const_cast<void*>(static_cast<const void*>(&opdata3)), OP_SOFTMAX, },
};
static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBuffer(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  if (current_location - bytes < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}
typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;
static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArena(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBuffer(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBuffer(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static TfLiteTensor* GetTensor(const struct TfLiteContext* context,
                               int tensor_idx) {
  return &tflTensors[tensor_idx];
}

static TfLiteEvalTensor* GetEvalTensor(const struct TfLiteContext* context,
                                       int tensor_idx) {
  return &tflEvalTensors[tensor_idx];
}

} // namespace

TfLiteStatus trained_model_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;
  ctx.AllocatePersistentBuffer = &AllocatePersistentBuffer;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArena;
  ctx.GetScratchBuffer = &GetScratchBuffer;
  ctx.GetTensor = &GetTensor;
  ctx.GetEvalTensor = &GetEvalTensor;
  ctx.tensors = tflTensors;
  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    tflTensors[i].type = tensorData[i].type;
    tflEvalTensors[i].type = tensorData[i].type;
    tflTensors[i].is_variable = 0;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
    tflTensors[i].allocation_type = tensorData[i].allocation_type;
#else
    tflTensors[i].allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
    tflTensors[i].bytes = tensorData[i].bytes;
    tflTensors[i].dims = tensorData[i].dims;
    tflEvalTensors[i].dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
    if(tflTensors[i].allocation_type == kTfLiteArenaRw){
      uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

     tflTensors[i].data.data =  start;
     tflEvalTensors[i].data.data =  start;
    }
    else {
       tflTensors[i].data.data = tensorData[i].data;
       tflEvalTensors[i].data.data = tensorData[i].data;
    }
#else
    tflTensors[i].data.data = tensorData[i].data;
    tflEvalTensors[i].data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
    tflTensors[i].quantization = tensorData[i].quantization;
    if (tflTensors[i].quantization.type == kTfLiteAffineQuantization) {
      TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
      tflTensors[i].params.scale = quant->scale->data[0];
      tflTensors[i].params.zero_point = quant->zero_point->data[0];
    }
    if (tflTensors[i].allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tflTensors[i].data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }
  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t i = 0; i < 4; ++i) {
    tflNodes[i].inputs = nodeData[i].inputs;
    tflNodes[i].outputs = nodeData[i].outputs;
    tflNodes[i].builtin_data = nodeData[i].builtin_data;
tflNodes[i].custom_initial_data = nullptr;
      tflNodes[i].custom_initial_data_size = 0;
if (registrations[nodeData[i].used_op_index].init) {
      tflNodes[i].user_data = registrations[nodeData[i].used_op_index].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
    }
  }
  for (size_t i = 0; i < 4; ++i) {
    if (registrations[nodeData[i].used_op_index].prepare) {
      TfLiteStatus status = registrations[nodeData[i].used_op_index].prepare(&ctx, &tflNodes[i]);
      if (status != kTfLiteOk) {
        return status;
      }
    }
  }
  return kTfLiteOk;
}

static const int inTensorIndices[] = {
  0, 
};
TfLiteTensor* trained_model_input(int index) {
  return &ctx.tensors[inTensorIndices[index]];
}

static const int outTensorIndices[] = {
  10, 
};
TfLiteTensor* trained_model_output(int index) {
  return &ctx.tensors[outTensorIndices[index]];
}

TfLiteStatus trained_model_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    TfLiteStatus status = registrations[nodeData[i].used_op_index].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus trained_model_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
